import {
  Apple,
  BatteryLow,
  Bike,
  BookOpen,
  Briefcase,
  Clock,
  CloudRain,
  Cpu,
  Drama,
  Flame,
  FlaskConical,
  Gem,
  Hammer,
  Handshake,
  Heart,
  HeartHandshake,
  HeartPulse,
  Laptop,
  MessageCircle,
  Moon,
  Paintbrush,
  Palette,
  PartyPopper,
  RefreshCw,
  Scale,
  School,
  Search,
  Shield,
  Sparkles,
  Users,
  Waves,
  type LucideIcon,
} from "lucide-react";

export const TOPIC_ICONS: Record<string, LucideIcon> = {
  heart: Heart,
  handshake: Handshake,
  "message-circle": MessageCircle,
  shield: Shield,
  users: Users,
  gem: Gem,
  moon: Moon,
  apple: Apple,
  bike: Bike,
  "heart-pulse": HeartPulse,
  laptop: Laptop,
  clock: Clock,
  "party-popper": PartyPopper,
  "book-open": BookOpen,
  flame: Flame,
  "heart-handshake": HeartHandshake,
  hammer: Hammer,
  sparkles: Sparkles,
  search: Search,
  "refresh-cw": RefreshCw,
  palette: Palette,
  school: School,
  cpu: Cpu,
  "flask-conical": FlaskConical,
  paintbrush: Paintbrush,
  drama: Drama,
  briefcase: Briefcase,
  "battery-low": BatteryLow,
  scale: Scale,
  "cloud-rain": CloudRain,
  "hand-helping": HeartHandshake,
  waves: Waves,
};

export function TopicIcon({ name, size = 18 }: { name: string; size?: number }) {
  const Icon = TOPIC_ICONS[name] ?? Heart;
  return <Icon size={size} strokeWidth={1.7} />;
}
